### ISSUE TITLE
terraform plan fail - chapter 1 

### ISSUE THREAD

**Issue by julianwieg** [Armitagency/cloud-native-security-cookbook-tf#1]
Hi,
I hope you can help. I am fairly nooby when it comes to this. 

I do have my github project setup with a Terraform Cloud VCS setup and I do have my GCP org also.

When I try "Scalable Project Structures on GCP" I get in the terraform plan the following error:

`Error: Error when reading or editing Folder Not Found : folders/Production: googleapi: Error 400: Request contains an invalid argument., badRequest
with data.google_folder.production
on main.tf line 14, in data "google_folder" "production":`

I would assume this error is either that the service account that terraform uses does not have the right permissions (I am sure it does) .      In GCP itself this folder does exist.  

My Repo and the correct branch is here:
https://github.com/julianwieg/gcp-terraform-learning/

**Comment by julianwieg** [comment]
Well ok, this was obviously. You have to use the folder IDs not folder names (kinda obvious when a GCP admin pointed it out at work).  However, as all the variable names and comments say 'folder name' of course the folder name is the input I gave.
Maybe update the comments and code so the next person does not get suck

**Comment by JoshArmi** [comment]
I'll add that to the errata, thank you
